accounts:
  - name: validator1
    coins: ["10000000ssvt"]
  - name: jacob
    coins: ["10000000ssvt"]
validator:
  name: validator1
  staked: "1000000ssvt"
client:
  openapi:
    path: "docs/static/openapi.yml"
init:
  client:
    keyring-backend: "test"
    chain-id: "cosmos:smpl-secrets-vault"
  config:
    consensus:
      create_empty_blocks: false
      create_empty_blocks_interval: "0s"
genesis:
  chain_id: "cosmos:smpl-secrets-vault"
  app_state:
    staking:
      params:
        bond_denom: "ssvt"
    crisis:
      constant_fee:
        denom: ssvt
    mint:
      params:
        mint_denom: ssvt