// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: smplsecretsvaultchain/wallets.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Wallets struct {
	Owner               string                    `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	WalletStorageMap    map[string]*WalletStorage `protobuf:"bytes,2,rep,name=walletStorageMap,proto3" json:"walletStorageMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	TestPhrase          string                    `protobuf:"bytes,3,opt,name=testPhrase,proto3" json:"testPhrase,omitempty"`
	EncryptedTestPhrase string                    `protobuf:"bytes,4,opt,name=encryptedTestPhrase,proto3" json:"encryptedTestPhrase,omitempty"`
}

func (m *Wallets) Reset()         { *m = Wallets{} }
func (m *Wallets) String() string { return proto.CompactTextString(m) }
func (*Wallets) ProtoMessage()    {}
func (*Wallets) Descriptor() ([]byte, []int) {
	return fileDescriptor_4e87d7322147efde, []int{0}
}
func (m *Wallets) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Wallets) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Wallets.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Wallets) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Wallets.Merge(m, src)
}
func (m *Wallets) XXX_Size() int {
	return m.Size()
}
func (m *Wallets) XXX_DiscardUnknown() {
	xxx_messageInfo_Wallets.DiscardUnknown(m)
}

var xxx_messageInfo_Wallets proto.InternalMessageInfo

func (m *Wallets) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Wallets) GetWalletStorageMap() map[string]*WalletStorage {
	if m != nil {
		return m.WalletStorageMap
	}
	return nil
}

func (m *Wallets) GetTestPhrase() string {
	if m != nil {
		return m.TestPhrase
	}
	return ""
}

func (m *Wallets) GetEncryptedTestPhrase() string {
	if m != nil {
		return m.EncryptedTestPhrase
	}
	return ""
}

func init() {
	proto.RegisterType((*Wallets)(nil), "SmplEcosystem.smplsecretsvaultchain.smplsecretsvaultchain.Wallets")
	proto.RegisterMapType((map[string]*WalletStorage)(nil), "SmplEcosystem.smplsecretsvaultchain.smplsecretsvaultchain.Wallets.WalletStorageMapEntry")
}

func init() {
	proto.RegisterFile("smplsecretsvaultchain/wallets.proto", fileDescriptor_4e87d7322147efde)
}

var fileDescriptor_4e87d7322147efde = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2e, 0xce, 0x2d, 0xc8,
	0x29, 0x4e, 0x4d, 0x2e, 0x4a, 0x2d, 0x29, 0x2e, 0x4b, 0x2c, 0xcd, 0x29, 0x49, 0xce, 0x48, 0xcc,
	0xcc, 0xd3, 0x2f, 0x4f, 0xcc, 0xc9, 0x49, 0x2d, 0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xb2, 0x0c, 0xce, 0x2d, 0xc8, 0x71, 0x4d, 0xce, 0x2f, 0xae, 0x2c, 0x2e, 0x49, 0xcd, 0xd5, 0xc3,
	0xaa, 0x05, 0xbb, 0xa8, 0x94, 0x16, 0x3e, 0xf3, 0xe3, 0x8b, 0x4b, 0xf2, 0x8b, 0x12, 0xd3, 0x53,
	0x21, 0xd6, 0x28, 0x75, 0x30, 0x73, 0xb1, 0x87, 0x43, 0x2c, 0x16, 0x12, 0xe1, 0x62, 0xcd, 0x2f,
	0xcf, 0x4b, 0x2d, 0x92, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x82, 0x70, 0x84, 0x5a, 0x18, 0xb9,
	0x04, 0x20, 0x5a, 0x83, 0x21, 0x3a, 0x7d, 0x13, 0x0b, 0x24, 0x98, 0x14, 0x98, 0x35, 0xb8, 0x8d,
	0x22, 0xf4, 0xc8, 0x76, 0xa4, 0x1e, 0xd4, 0x52, 0x28, 0x8d, 0x30, 0xda, 0x35, 0xaf, 0xa4, 0xa8,
	0x32, 0x08, 0xc3, 0x46, 0x21, 0x39, 0x2e, 0xae, 0x92, 0xd4, 0xe2, 0x92, 0x80, 0x8c, 0xa2, 0xc4,
	0xe2, 0x54, 0x09, 0x66, 0xb0, 0x0b, 0x91, 0x44, 0x84, 0x0c, 0xb8, 0x84, 0x53, 0xf3, 0x92, 0x8b,
	0x2a, 0x0b, 0x4a, 0x52, 0x53, 0x42, 0x10, 0x0a, 0x59, 0xc0, 0x0a, 0xb1, 0x49, 0x49, 0xf5, 0x32,
	0x72, 0x89, 0x62, 0xb5, 0x5d, 0x48, 0x80, 0x8b, 0x39, 0x3b, 0xb5, 0x12, 0x1a, 0x0c, 0x20, 0xa6,
	0x50, 0x1c, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69, 0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0xb7, 0x91,
	0x07, 0xc5, 0x1e, 0x87, 0x5a, 0x19, 0x04, 0x31, 0xd6, 0x8a, 0xc9, 0x82, 0xd1, 0x29, 0xed, 0xc4,
	0x23, 0x39, 0xc6, 0x0b, 0x8f, 0xe4, 0x18, 0x1f, 0x3c, 0x92, 0x63, 0x9c, 0xf0, 0x58, 0x8e, 0xe1,
	0xc2, 0x63, 0x39, 0x86, 0x1b, 0x8f, 0xe5, 0x18, 0xa2, 0x7c, 0xd2, 0x33, 0x4b, 0x32, 0x4a, 0x93,
	0xf4, 0x92, 0xf3, 0x73, 0xf5, 0x51, 0x2c, 0x06, 0xf3, 0x82, 0x21, 0x56, 0x84, 0x81, 0xac, 0x70,
	0x06, 0xc7, 0x74, 0x85, 0x3e, 0xf6, 0x14, 0x50, 0x52, 0x59, 0x90, 0x5a, 0x9c, 0xc4, 0x06, 0x8e,
	0x79, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaa, 0xc6, 0xee, 0xbe, 0x87, 0x02, 0x00, 0x00,
}

func (m *Wallets) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Wallets) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Wallets) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EncryptedTestPhrase) > 0 {
		i -= len(m.EncryptedTestPhrase)
		copy(dAtA[i:], m.EncryptedTestPhrase)
		i = encodeVarintWallets(dAtA, i, uint64(len(m.EncryptedTestPhrase)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TestPhrase) > 0 {
		i -= len(m.TestPhrase)
		copy(dAtA[i:], m.TestPhrase)
		i = encodeVarintWallets(dAtA, i, uint64(len(m.TestPhrase)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.WalletStorageMap) > 0 {
		for k := range m.WalletStorageMap {
			v := m.WalletStorageMap[k]
			baseI := i
			if v != nil {
				{
					size, err := v.MarshalToSizedBuffer(dAtA[:i])
					if err != nil {
						return 0, err
					}
					i -= size
					i = encodeVarintWallets(dAtA, i, uint64(size))
				}
				i--
				dAtA[i] = 0x12
			}
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintWallets(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintWallets(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintWallets(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintWallets(dAtA []byte, offset int, v uint64) int {
	offset -= sovWallets(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Wallets) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovWallets(uint64(l))
	}
	if len(m.WalletStorageMap) > 0 {
		for k, v := range m.WalletStorageMap {
			_ = k
			_ = v
			l = 0
			if v != nil {
				l = v.Size()
				l += 1 + sovWallets(uint64(l))
			}
			mapEntrySize := 1 + len(k) + sovWallets(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovWallets(uint64(mapEntrySize))
		}
	}
	l = len(m.TestPhrase)
	if l > 0 {
		n += 1 + l + sovWallets(uint64(l))
	}
	l = len(m.EncryptedTestPhrase)
	if l > 0 {
		n += 1 + l + sovWallets(uint64(l))
	}
	return n
}

func sovWallets(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWallets(x uint64) (n int) {
	return sovWallets(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Wallets) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWallets
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Wallets: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Wallets: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWallets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWallets
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWallets
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WalletStorageMap", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWallets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWallets
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWallets
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.WalletStorageMap == nil {
				m.WalletStorageMap = make(map[string]*WalletStorage)
			}
			var mapkey string
			var mapvalue *WalletStorage
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowWallets
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowWallets
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthWallets
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthWallets
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowWallets
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthWallets
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthWallets
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &WalletStorage{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipWallets(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthWallets
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.WalletStorageMap[mapkey] = mapvalue
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TestPhrase", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWallets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWallets
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWallets
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TestPhrase = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptedTestPhrase", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWallets
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWallets
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWallets
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncryptedTestPhrase = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWallets(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWallets
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWallets(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWallets
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWallets
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWallets
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWallets
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWallets
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWallets
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWallets        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWallets          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWallets = fmt.Errorf("proto: unexpected end of group")
)
