// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: smplsecretsvaultchain/wallet_storage.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type WalletStorage struct {
	Wallet              *Wallet `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	TestPhrase          string  `protobuf:"bytes,2,opt,name=testPhrase,proto3" json:"testPhrase,omitempty"`
	EncryptedTestPhrase string  `protobuf:"bytes,3,opt,name=encryptedTestPhrase,proto3" json:"encryptedTestPhrase,omitempty"`
}

func (m *WalletStorage) Reset()         { *m = WalletStorage{} }
func (m *WalletStorage) String() string { return proto.CompactTextString(m) }
func (*WalletStorage) ProtoMessage()    {}
func (*WalletStorage) Descriptor() ([]byte, []int) {
	return fileDescriptor_911dc7cfb18f39bb, []int{0}
}
func (m *WalletStorage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *WalletStorage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_WalletStorage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *WalletStorage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WalletStorage.Merge(m, src)
}
func (m *WalletStorage) XXX_Size() int {
	return m.Size()
}
func (m *WalletStorage) XXX_DiscardUnknown() {
	xxx_messageInfo_WalletStorage.DiscardUnknown(m)
}

var xxx_messageInfo_WalletStorage proto.InternalMessageInfo

func (m *WalletStorage) GetWallet() *Wallet {
	if m != nil {
		return m.Wallet
	}
	return nil
}

func (m *WalletStorage) GetTestPhrase() string {
	if m != nil {
		return m.TestPhrase
	}
	return ""
}

func (m *WalletStorage) GetEncryptedTestPhrase() string {
	if m != nil {
		return m.EncryptedTestPhrase
	}
	return ""
}

func init() {
	proto.RegisterType((*WalletStorage)(nil), "SmplEcosystem.smplsecretsvaultchain.smplsecretsvaultchain.WalletStorage")
}

func init() {
	proto.RegisterFile("smplsecretsvaultchain/wallet_storage.proto", fileDescriptor_911dc7cfb18f39bb)
}

var fileDescriptor_911dc7cfb18f39bb = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2a, 0xce, 0x2d, 0xc8,
	0x29, 0x4e, 0x4d, 0x2e, 0x4a, 0x2d, 0x29, 0x2e, 0x4b, 0x2c, 0xcd, 0x29, 0x49, 0xce, 0x48, 0xcc,
	0xcc, 0xd3, 0x2f, 0x4f, 0xcc, 0xc9, 0x49, 0x2d, 0x89, 0x2f, 0x2e, 0xc9, 0x2f, 0x4a, 0x4c, 0x4f,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xb2, 0x0c, 0xce, 0x2d, 0xc8, 0x71, 0x4d, 0xce, 0x2f,
	0xae, 0x2c, 0x2e, 0x49, 0xcd, 0xd5, 0xc3, 0xaa, 0x13, 0xbb, 0xa8, 0x94, 0x12, 0x3e, 0x6b, 0x20,
	0xc6, 0x2b, 0xed, 0x61, 0xe4, 0xe2, 0x0d, 0x07, 0x0b, 0x04, 0x43, 0xac, 0x15, 0x8a, 0xe4, 0x62,
	0x83, 0xa8, 0x90, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x36, 0x72, 0xd4, 0x23, 0xdb, 0x05, 0x7a, 0x10,
	0x93, 0x83, 0xa0, 0x06, 0x0a, 0xc9, 0x71, 0x71, 0x95, 0xa4, 0x16, 0x97, 0x04, 0x64, 0x14, 0x25,
	0x16, 0xa7, 0x4a, 0x30, 0x29, 0x30, 0x6a, 0x70, 0x06, 0x21, 0x89, 0x08, 0x19, 0x70, 0x09, 0xa7,
	0xe6, 0x25, 0x17, 0x55, 0x16, 0x94, 0xa4, 0xa6, 0x84, 0x20, 0x14, 0x32, 0x83, 0x15, 0x62, 0x93,
	0x72, 0x4a, 0x3b, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23, 0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x27,
	0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6, 0x63, 0x39, 0x86, 0x28, 0x9f, 0xf4, 0xcc,
	0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0x7d, 0x14, 0x0f, 0x80, 0x79, 0xc1, 0x10, 0xa7,
	0x86, 0x81, 0x9c, 0xea, 0x0c, 0x0e, 0x95, 0x0a, 0x7d, 0xec, 0xa1, 0x55, 0x52, 0x59, 0x90, 0x5a,
	0x9c, 0xc4, 0x06, 0x0e, 0x2d, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8b, 0x76, 0xa5, 0xe7,
	0xba, 0x01, 0x00, 0x00,
}

func (m *WalletStorage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *WalletStorage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *WalletStorage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.EncryptedTestPhrase) > 0 {
		i -= len(m.EncryptedTestPhrase)
		copy(dAtA[i:], m.EncryptedTestPhrase)
		i = encodeVarintWalletStorage(dAtA, i, uint64(len(m.EncryptedTestPhrase)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TestPhrase) > 0 {
		i -= len(m.TestPhrase)
		copy(dAtA[i:], m.TestPhrase)
		i = encodeVarintWalletStorage(dAtA, i, uint64(len(m.TestPhrase)))
		i--
		dAtA[i] = 0x12
	}
	if m.Wallet != nil {
		{
			size, err := m.Wallet.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintWalletStorage(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintWalletStorage(dAtA []byte, offset int, v uint64) int {
	offset -= sovWalletStorage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *WalletStorage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Wallet != nil {
		l = m.Wallet.Size()
		n += 1 + l + sovWalletStorage(uint64(l))
	}
	l = len(m.TestPhrase)
	if l > 0 {
		n += 1 + l + sovWalletStorage(uint64(l))
	}
	l = len(m.EncryptedTestPhrase)
	if l > 0 {
		n += 1 + l + sovWalletStorage(uint64(l))
	}
	return n
}

func sovWalletStorage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWalletStorage(x uint64) (n int) {
	return sovWalletStorage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *WalletStorage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWalletStorage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: WalletStorage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: WalletStorage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Wallet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalletStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWalletStorage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWalletStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Wallet == nil {
				m.Wallet = &Wallet{}
			}
			if err := m.Wallet.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TestPhrase", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalletStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalletStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalletStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TestPhrase = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptedTestPhrase", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWalletStorage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWalletStorage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWalletStorage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncryptedTestPhrase = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWalletStorage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWalletStorage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWalletStorage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWalletStorage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWalletStorage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWalletStorage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWalletStorage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWalletStorage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWalletStorage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWalletStorage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWalletStorage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWalletStorage = fmt.Errorf("proto: unexpected end of group")
)
